Update Sync.yml

diff --git a/.github/workflows/Sync.yml b/.github/workflows/Sync.yml
--- a/.github/workflows/Sync.yml
+++ b/.github/workflows/Sync.yml
@@ -1,34 +1,34 @@
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  schedule:
-    - cron: '0 0 * * *'   # 每天 0 点自动运行（UTC 时间）
-  workflow_dispatch:       # 手动触发按钮
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
 
 jobs:
-  sync:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          persist-credentials: false
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
-      - name: Set Git config
-        run: |
-          git config --global user.name "GitHub Actions"
-          git config --global user.email "actions@github.com"
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
 
-      - name: Add upstream
-        run: |
-          git remote add upstream https://github.com/senshinya/MoonTV.git
-          git fetch upstream
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+                  upstream_sync_repo: senshinya/MoonTV
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
 
-      - name: Merge upstream changes
-        run: |
-          git checkout main        # 如果你的默认分支叫 master，则改成 master
-          git merge upstream/main  # 如果上游默认分支叫 master，则改成 upstream/master
-
-      - name: Push changes
-        run: |
-          git push origin main
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
